### ISSUE TITLE
Image Background Color

### ISSUE THREAD

**Issue by millportmedia** [aautio/react-modal-image#10]
I love this component but I would like to be able to set a background color for the modal. I have a large library of png images with a transparent background. These look fine on the white background on the page in their small version but when enlarged show a transparent background that is visually unappealing. Any suggestions?

**Comment by aautio** [comment]
@millportmedia I've made two additions to make transparent png images look nicer:

1. The background color of the images is black by default.
2. If black is not suitable for your images you can change it to something else with a new prop called `imageBackgroundColor`

The commit is here https://github.com/aautio/react-modal-image/commit/2638f40aa2472ab5fc1a48af629d0dfe2f0c9272

I've planned to update the demo site and NPM package to be updated later today.

Would this look like something that would work for you?

**Comment by aautio** [comment]
Version `2.4.0` was just been published to NPM. See the demo site with the second last image for a demo of the new background image property: https://aautio.github.io/react-modal-image/
