### ISSUE TITLE
Clicking the close button scrolls to the top of the page.

### ISSUE THREAD

**Issue by volkandkaya** [aautio/react-modal-image#15]
Closing the modal by clicking the X scrolls to the top of the page. Works fine when closed using escape.

**Comment by aautio** [comment]
I'm unable to reproduce this.

@volkandkaya would you elaborate - what browser are you using?

I've tested this with iOS Safari on an iPhone and with Google Chrome on Mac OS X. They do not scroll to the top of the page. I've tested this at the demo site: https://aautio.github.io/react-modal-image/

**Comment by volkandkaya** [comment]
Can't replicate outside of local. Will close ticket.
