### ISSUE TITLE
Close button scroll up the page

### ISSUE THREAD

**Issue by volkandkaya** [aautio/react-modal-image#18]
Try to click the close button top https://saaspages.xyz/

https://github.com/volkandkaya/saaspages

**Comment by aautio** [comment]
Hi @volkandkaya - I've checked your page. Clicking the close-button does not scroll to top. I've verified this with Chrome, Firefox and Safari. I'm closing the issue. 

Please leave a comment or reopen with more info if you think there is an actual bug.
