### ISSUE TITLE
Handle broken images

### ISSUE THREAD

**Issue by serfgy** [aautio/react-modal-image#2]
Is there a method to handle broken images? Broken images can be fixed by using the onerror method on the img tag, but since image url here is directly handled by the higher level component, how should we do this?

**Comment by aautio** [comment]
The current api does not yet provide a way to handle events (such as onerror). I'll need to think about this a bit.

What kinds of approaches would you take to fix the broken images? I mean what would you do within the onerror-method? Would you usually display an placeholder text or placeholder svg icon? Or some kind of a retry-link?

**Comment by aautio** [comment]
Closing the issue due to inactivity.
