### ISSUE TITLE
Issue : View config not found for name path . Make sure to start component names with a capital letter.

### ISSUE THREAD

**Issue by Anujmoglix** [aautio/react-modal-image#27]
Hi I am getting issue **Issue : View config not found for name path . Make sure to start component names with a capital letter..** My code is as following 

`  <View style={styles.imgWrap}>
                     <Lightbox
      medium={CONSTANTS.IMAGE_URL + item.data+ "_150" }
      large={CONSTANTS.IMAGE_URL + item.data}
      alt="Hello World!"
    />
</View>`

**Comment by aautio** [comment]
@Anujmoglix I'd assume this issue is not related to `react-modal-image`, but your framework instead? I'm closing the issue.
