### ISSUE TITLE
Any plans to update the React dependency version?

### ISSUE THREAD

**Issue by AllAroundD** [aautio/react-modal-image#39]
Hi, are there any plans to update the React dependency to version 17?

I'm getting the following error:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: client@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"16.x" from react-modal-image@2.5.0
npm ERR! node_modules/react-modal-image
npm ERR!   react-modal-image@"*" from the root project

I had to add the '-legacy-peer-deps' when installing.

**Comment by aautio** [comment]
I've just published `react-modal-image@2.6.0` which fixes this issue. Sorry for the long wait!
