### ISSUE TITLE
Proposal: Support for videos

### ISSUE THREAD

**Issue by raRaRa** [aautio/react-modal-image#4]
Proposal: Support for videos by utilizing the `<video>` element.

Could change the `<Image />` component to `<Media />`, which could have an attribute such as `isVideo`, which determines if it should display the media as `<img>` or `<video>`.

I could help with this, if this proposal is accepted.

**Comment by aautio** [comment]
Thank you @raRaRa for your proposal. I'll try to keep this component minimal and focused on images only. Thus any video support is out of scope for the component.
