### ISSUE TITLE
Proposal: Hide scrollbar when the Lightbox is visible

### ISSUE THREAD

**Issue by raRaRa** [aautio/react-modal-image#5]
Proposal: Hide scrollbar when the Lightbox is visible.

Most modals these days hide the scrollbar when they are open.

**Comment by aautio** [comment]
Oops, good idea! The scrollbars are not visible on macOS and thus I had missed this. I'll take care of this.

**Comment by aautio** [comment]
I've just published version 2.3.0 in npm. The scrollbar is now hidden.

The commit message has more details at https://github.com/aautio/react-modal-image/commit/b41225d8929fc66ff8f0013fc1c72bbd4f2cad72
