### ISSUE TITLE
I can't download image when using react-modal-image  when i press download icon display image in Browser instead of download it?

### ISSUE THREAD

**Issue by IIslam** [aautio/react-modal-image#6]
return (
                <div>
                    <p>
                        {label} :
                            <ModalImage
                            alt="Here is the caption"
                            small={url}
                            large={url}
                        />

                    </p>
                </div>

**Comment by aautio** [comment]
Hi @IIslam!

The file download is using html5 `dowload` -attribute to launch file download. It is not supported in Internet Explorer and iOS Safari: https://caniuse.com/#feat=download

But for other major browsers it should work. Which one are you using?

**Comment by aautio** [comment]
Closing the issue due to inactivity.
