### ISSUE TITLE
Importing components results in 'undefined'

### ISSUE THREAD

**Issue by fastingsamurai** [aautio/react-modal-image#7]
I did: npm install react-modal-image --save

When I import a component e.g. import { Lightbox } from "react-modal-image"; and use it I get the following error when the render() method is called:

React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `Lightbox`.

I looked at the compiled code in node_modules and it looks OK to me. Not sure what could be going on here as I probably use close to 50 react components in this project and have never seen this behavior before. Very strange.

**Comment by aautio** [comment]
Can you share some parts of your code and I can help you to isolate the problem?

**Comment by fastingsamurai** [comment]
I think I see the issue. Various components return <React.Fragment> from their render method. This doesn't seem to exist in React 15 so the result is they return undefined.

**Comment by aautio** [comment]
@fastingsamurai ah, sorry. It seems that I've introduced <React.Fragments> with version 2.3.0 thus breaking React 15 compatibility. I'll look into bringing back React 15 support with version 2.3.2.

In the mean time version 2.2.0 would be safe to use with React 15.

**Comment by aautio** [comment]
Versin 2.3.2 has been published. Now React 15 works with it. Sorry for the trouble @fastingsamurai.
