### ISSUE TITLE
onClose function not working

### ISSUE THREAD

**Issue by raheel036** [aautio/react-modal-image#8]
` <ModalImage
                small={val.location}
                 large={val.location}
                        alt=""
                        className="image_show"
                        onClose={this.closeLightbox}
                    /> `

closeLightbox = () => {
         console.log('test')
    };

**Comment by aautio** [comment]
Hi @raheel036!

The `onClose`-prop is not available with `<ModalImage>`.

The `onClose`-prop is only a part of lower level API. You can use `<Lightbox/>` if you want to fully control the state of the lightbox. The function provided shall be invoked when the `<Lightbox/>` requests to be closed.
