### ISSUE TITLE
z-index, material-ui

### ISSUE THREAD

**Issue by claytonfbell** [aautio/react-modal-image#9]
Is it possible to set the zIndex of the modal? It is displaying below material-ui components such as the AppBar.

**Comment by inform880** [comment]
I'm getting the same issue
![image](https://user-images.githubusercontent.com/6600519/60386679-6a2a2780-9a66-11e9-84ea-42dad06ece3c.png)

**Comment by aautio** [comment]
Perhaps adjusting the z-index would be enough. Hmm.

@inform880 is your site online somewhere to help me debug & fix the issue? I'll see what I can do.

**Comment by inform880** [comment]
I know this issue is months old, but if anyone else is having the issue like I am, you can fix it by setting a custom mui theme, like this: 

import React from "react";
import ReactDOM from "react-dom";

import { createMuiTheme, MuiThemeProvider } from "@material-ui/core/styles";

import { App } from "./App";

const theme = createMuiTheme({
  zIndex: {
// set these to whatever, I just set the appbar to 1
    mobileStepper: 1000
    appBar: 1100
    drawer: 1200
    modal: 1300
    snackbar: 1400
    tooltip: 1500
  }
});

function Index() {
  return (
    <MuiThemeProvider theme={theme}>
      <App />
    </MuiThemeProvider>
  );
}

**Comment by inform880** [comment]
@aautio I haven't done a release yet with this modal component yet, I can comment and let you know. I should be ready later today.

**Comment by inform880** [comment]
I dislike how mui sets these zindexes to arbitrarily high numbers, but you can find more info about it on this page, where they literally say they're set arbitrarily high: https://material-ui.com/customization/z-index/

**Comment by aautio** [comment]
Would it be safe to use a huge z-index (~5000) with the modal opened by react-modal-image? Do you see any downsides on the component providing the default value and not providing an override possibility?

**Comment by inform880** [comment]
I don't see an issue with that, that's literally what material-ui does for most components including their modal.

**Comment by Isaiaher** [comment]
Any news on this/ a work around? My image is showing up underneath my Navigation header as well in the expanded/large mode.

**Comment by aautio** [comment]
I've just published version `2.5.0` with `z-index` increased to 5000. I hope it helps with the material-ui issues.
